version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      every: 2
    open-pull-requests-limit: 5
    rebase-strategy: "auto"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
      every: 2
    open-pull-requests-limit: 5
    rebase-strategy: "auto"

allow:
  - dependency-type: "all"
