CREATE TABLE Users(
	Id INTEGER PRIMARY KEY IDENTITY(1,1),
	email VARCHAR(50) NOT NULL
);

CREATE TABLE Users_Roles(
	UserId INTEGER,
	RoleId INTEGER,
	PRIMARY KEY(UserId, RoleId)
);

CREATE TABLE Roles(
	Id INTEGER PRIMARY KEY IDENTITY(1,1),
	Name VARCHAR(50)
);