CREATE TABLE Users(
	Id INTEGER PRIMARY KEY IDENTITY(1,1),
	Email VARCHAR(255) not null UNIQUE,
	MoneySpent DECIMAL(10,2),
	CreatedAt DATETIME not null,
	FIRST VARCHAR(25),
	LAST VARCHAR(25),
	Bio VARCHAR(MAX) -- or TEXT
);