apiVersion: v1
kind: Pod
metadata:
  name: demo
spec:
  containers:
  - name: testpod
    image: alpine:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    command: ["ping", "8.8.8.8"]